import { useMemo, useState } from "react";
import { OqeraIcon, ProjectIcon, SearchIcon, GitIcon, IntelligenceIcon, TerminalIcon, SettingsIcon, CloseIcon } from "./icons";
import { FileTree } from "./components/explorer/FileTree";
import { CodeEditor } from "./components/editor/CodeEditor";
import { oqera } from "./lib/oqera";
import type { EditorTab, FileNode, Workspace } from "./types/workspace";

type Locale="en"|"ar";
const copy={en:{project:"PROJECT",explorer:"Explorer",search:"Search",git:"Source Control",intelligence:"Intelligence",runtime:"Runtime",terminal:"TERMINAL",problems:"PROBLEMS",output:"OUTPUT",tests:"TESTS",empty:"Open a project to start building.",open:"Open Project",settings:"Settings",save:"Save",opening:"Opening…"},ar:{project:"المشروع",explorer:"المستكشف",search:"البحث",git:"التحكم بالمصدر",intelligence:"الذكاء",runtime:"التشغيل",terminal:"الطرفية",problems:"المشكلات",output:"المخرجات",tests:"الاختبارات",empty:"افتح مشروعًا لبدء العمل.",open:"فتح مشروع",settings:"الإعدادات",save:"حفظ",opening:"جارٍ الفتح…"}} as const;

export function App(){
 const [locale,setLocale]=useState<Locale>("en"),[workspace,setWorkspace]=useState<Workspace|null>(null),[tabs,setTabs]=useState<EditorTab[]>([]),[active,setActive]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[closeCandidate,setCloseCandidate]=useState<string|null>(null);
 const t=copy[locale],rtl=locale==="ar",activeTab=useMemo(()=>tabs.find(x=>x.path===active)??null,[tabs,active]);
 const dirty=activeTab?activeTab.content!==activeTab.savedContent:false;
 async function openWorkspace(){setBusy(true);setError(null);try{const next=await oqera.workspace.open();if(next){setWorkspace(next);setTabs([]);setActive(null)}}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function openFile(node:FileNode){if(node.kind!=="file")return;const existing=tabs.find(x=>x.path===node.path);if(existing){setActive(node.path);return}setError(null);try{const content=await oqera.fs.readFile(node.path);setTabs(old=>[...old,{path:node.path,name:node.name,content,savedContent:content}]);setActive(node.path)}catch(e){setError(String(e))}}
 async function save(contentOverride?:string){if(!activeTab)return;const content=contentOverride??activeTab.content;if(content===activeTab.savedContent)return;setError(null);try{await oqera.fs.writeFile(activeTab.path,content);setTabs(old=>old.map(x=>x.path===activeTab.path?{...x,content,savedContent:content}:x))}catch(e){setError(String(e))}}
 function closeTab(path:string){const tab=tabs.find(x=>x.path===path);if(tab&&tab.content!==tab.savedContent){setCloseCandidate(path);return}closeTabNow(path)}
 function closeTabNow(path:string){setTabs(old=>{const index=old.findIndex(x=>x.path===path),next=old.filter(x=>x.path!==path);if(active===path)setActive(next[Math.min(index,next.length-1)]?.path??null);return next});setCloseCandidate(null)}
 async function saveAndClose(){if(!closeCandidate)return;const tab=tabs.find(x=>x.path===closeCandidate);if(!tab){setCloseCandidate(null);return}setError(null);try{await oqera.fs.writeFile(tab.path,tab.content);closeTabNow(tab.path)}catch(e){setError(String(e));setCloseCandidate(null)}}
 return <main className="app" dir={rtl?"rtl":"ltr"}>
 <header className="titlebar"><div className="brand"><OqeraIcon/><strong>OQERA</strong></div><div className="project-title">{workspace?.name??"Oqera Workspace"}{dirty?" •":""}</div><div className="title-actions"><button className="locale" onClick={()=>setLocale(rtl?"en":"ar")}>{rtl?"EN":"عربي"}</button><button className="icon-button" aria-label={t.settings}><SettingsIcon/></button></div></header>
 <section className="workspace"><nav className="activitybar"><Tool label={t.explorer}><ProjectIcon/></Tool><Tool label={t.search}><SearchIcon/></Tool><Tool label={t.git}><GitIcon/></Tool><Tool label={t.intelligence}><IntelligenceIcon/></Tool><Tool label={t.runtime}><TerminalIcon/></Tool></nav>
 <aside className="sidebar"><div className="panel-heading"><span>{workspace?.name.toUpperCase()??t.project}</span>{workspace?<button className="mini-action" onClick={openWorkspace}>•••</button>:null}</div>{workspace?<FileTree nodes={workspace.entries} onOpen={openFile}/>:<div className="empty-side"><ProjectIcon/><span>{t.empty}</span><button onClick={openWorkspace} disabled={busy}>{busy?t.opening:t.open}</button></div>}</aside>
 <section className="editor"><div className="editor-tabs">{tabs.length?tabs.map(tab=>{const isDirty=tab.content!==tab.savedContent;return <button key={tab.path} className={"tab "+(active===tab.path?"active":"")} onClick={()=>setActive(tab.path)}><span className="tab-name">{tab.name}</span><span className="tab-close" onClick={e=>{e.stopPropagation();closeTab(tab.path)}}>{isDirty?<span className="dirty-close">●</span>:<CloseIcon/>}</span></button>}):<div className="tab active">Welcome</div>}</div>
 {error?<div className="error-banner">{error}<button onClick={()=>setError(null)}>×</button></div>:null}
 {activeTab?<><div className="breadcrumb" dir="ltr">{workspace?.name} / {activeTab.path}</div><CodeEditor key={activeTab.path} tab={activeTab} onChange={value=>setTabs(old=>old.map(x=>x.path===activeTab.path?{...x,content:value}:x))} onSave={save}/></>:<div className="welcome"><OqeraIcon size={54}/><h1>Oqera</h1><p>{t.empty}</p><button className="primary" onClick={openWorkspace} disabled={busy}>{busy?t.opening:t.open}</button><div className="hint"><kbd>⌘</kbd><kbd>K</kbd><span>Command Center</span></div></div>}</section></section>
 {closeCandidate?<div className="modal-backdrop" onMouseDown={()=>setCloseCandidate(null)}><div className="save-dialog" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><div className="dialog-icon">!</div><div className="dialog-copy"><h2>{rtl?"حفظ التغييرات؟":"Save changes?"}</h2><p>{rtl?`لديك تغييرات غير محفوظة في ${tabs.find(x=>x.path===closeCandidate)?.name??""}.`:`You have unsaved changes in ${tabs.find(x=>x.path===closeCandidate)?.name??""}.`}</p></div><div className="dialog-actions"><button onClick={()=>setCloseCandidate(null)}>{rtl?"إلغاء":"Cancel"}</button><button className="danger-action" onClick={()=>closeTabNow(closeCandidate)}>{rtl?"عدم الحفظ":"Don't Save"}</button><button className="primary" onClick={()=>void saveAndClose()}>{rtl?"حفظ":"Save"}</button></div></div></div>:null}
 <section className="bottom"><div className="bottom-tabs"><span className="active">{t.terminal}</span><span>{t.problems}</span><span>{t.output}</span><span>{t.tests}</span></div><div className="terminal">$ <span className="muted">Oqera terminal will appear here.</span></div></section>
 <footer className="status"><span>⎇ main</span><span>✓ 0</span>{activeTab?<span>{dirty?"● Modified":"Saved"}</span>:null}<span className="grow"/><span>{activeTab?.path??"Oqera 0.2.0"}</span></footer></main>
}
function Tool({label,children}:{label:string;children:React.ReactNode}){return <button className="tool" title={label} aria-label={label}>{children}</button>}
